// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsWebsiteExercise.Models;

#nullable disable

namespace NewsWebsiteExercise.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NewsWebsiteExercise.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pets"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wildlife"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Culinary"
                        });
                });

            modelBuilder.Entity("NewsWebsiteExercise.Models.Entities.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Local wolf lady Sejt was found this morning doing the amogus twerk at park, gathering a large crowd of observers.",
                            Title = "Sejt has the moves!"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "According to local cat expert Riche Shinta \"Cats are the most trustworthy animals of all time, and they definitely deserve a bit of salami every now and then, as a treat.\"",
                            Title = "Cats, should you trust them?"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "He's a good boy. That's it, that's the whole article, everything past riodoche migration will just have placeholder Lorem Ipsum text.",
                            Title = "Why you should forfeit all mortal posessions to Seth"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Early this Monday, the local Riodoche population has begun their yearly migration up the mountain stream, where thousands of Famiries will form Staccs and Triamgles while vibin' in the tall grass.",
                            Title = "Riodoche migration going smoothly."
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque imperdiet auctor erat, id varius ipsum. Phasellus eget augue vestibulum, rutrum turpis eu, tempor mauris. Etiam commodo ligula sit amet mauris scelerisque efficitur. Aenean sit amet lobortis lacus, vitae placerat erat. Aliquam erat volutpat. Etiam luctus, massa ac bibendum eleifend, odio elit mollis purus, et blandit dui nulla quis ex. Nunc quis luctus velit. Pellentesque varius sollicitudin magna, nec fermentum felis vehicula sed. Sed cursus magna vitae augue feugiat, a ultrices enim varius. Proin tempus felis ut pulvinar viverra. Nulla vestibulum nibh in mauris imperdiet varius. Fusce imperdiet viverra libero id malesuada. Morbi pellentesque cursus efficitur. Sed fermentum sagittis mauris. Nulla laoreet ligula ut varius tempor.",
                            Title = "Tribal rabbits? Everything you need to know!"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque imperdiet auctor erat, id varius ipsum. Phasellus eget augue vestibulum, rutrum turpis eu, tempor mauris. Etiam commodo ligula sit amet mauris scelerisque efficitur. Aenean sit amet lobortis lacus, vitae placerat erat. Aliquam erat volutpat. Etiam luctus, massa ac bibendum eleifend, odio elit mollis purus, et blandit dui nulla quis ex. Nunc quis luctus velit. Pellentesque varius sollicitudin magna, nec fermentum felis vehicula sed. Sed cursus magna vitae augue feugiat, a ultrices enim varius. Proin tempus felis ut pulvinar viverra. Nulla vestibulum nibh in mauris imperdiet varius. Fusce imperdiet viverra libero id malesuada. Morbi pellentesque cursus efficitur. Sed fermentum sagittis mauris. Nulla laoreet ligula ut varius tempor.",
                            Title = "Woman falls in love with giant monkey."
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque imperdiet auctor erat, id varius ipsum. Phasellus eget augue vestibulum, rutrum turpis eu, tempor mauris. Etiam commodo ligula sit amet mauris scelerisque efficitur. Aenean sit amet lobortis lacus, vitae placerat erat. Aliquam erat volutpat. Etiam luctus, massa ac bibendum eleifend, odio elit mollis purus, et blandit dui nulla quis ex. Nunc quis luctus velit. Pellentesque varius sollicitudin magna, nec fermentum felis vehicula sed. Sed cursus magna vitae augue feugiat, a ultrices enim varius. Proin tempus felis ut pulvinar viverra. Nulla vestibulum nibh in mauris imperdiet varius. Fusce imperdiet viverra libero id malesuada. Morbi pellentesque cursus efficitur. Sed fermentum sagittis mauris. Nulla laoreet ligula ut varius tempor.",
                            Title = "Bug lady reveals secret to her family restaurant's delicious stews"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque imperdiet auctor erat, id varius ipsum. Phasellus eget augue vestibulum, rutrum turpis eu, tempor mauris. Etiam commodo ligula sit amet mauris scelerisque efficitur. Aenean sit amet lobortis lacus, vitae placerat erat. Aliquam erat volutpat. Etiam luctus, massa ac bibendum eleifend, odio elit mollis purus, et blandit dui nulla quis ex. Nunc quis luctus velit. Pellentesque varius sollicitudin magna, nec fermentum felis vehicula sed. Sed cursus magna vitae augue feugiat, a ultrices enim varius. Proin tempus felis ut pulvinar viverra. Nulla vestibulum nibh in mauris imperdiet varius. Fusce imperdiet viverra libero id malesuada. Morbi pellentesque cursus efficitur. Sed fermentum sagittis mauris. Nulla laoreet ligula ut varius tempor.",
                            Title = "Hyper realistic fitness cake shocks party goers"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque imperdiet auctor erat, id varius ipsum. Phasellus eget augue vestibulum, rutrum turpis eu, tempor mauris. Etiam commodo ligula sit amet mauris scelerisque efficitur. Aenean sit amet lobortis lacus, vitae placerat erat. Aliquam erat volutpat. Etiam luctus, massa ac bibendum eleifend, odio elit mollis purus, et blandit dui nulla quis ex. Nunc quis luctus velit. Pellentesque varius sollicitudin magna, nec fermentum felis vehicula sed. Sed cursus magna vitae augue feugiat, a ultrices enim varius. Proin tempus felis ut pulvinar viverra. Nulla vestibulum nibh in mauris imperdiet varius. Fusce imperdiet viverra libero id malesuada. Morbi pellentesque cursus efficitur. Sed fermentum sagittis mauris. Nulla laoreet ligula ut varius tempor.",
                            Title = "Bugsnax and how to avoid them"
                        });
                });

            modelBuilder.Entity("NewsWebsiteExercise.Models.Entities.News", b =>
                {
                    b.HasOne("NewsWebsiteExercise.Models.Entities.Category", "Category")
                        .WithMany("News")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NewsWebsiteExercise.Models.Entities.Category", b =>
                {
                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
